name: 'Unit Tests & Static Analysis'

on:
  push:
    branches: [ release-2.x, release-3.x ]
  pull_request:
    branches: [ release-2.x, release-3.x ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: 8.2
          extensions: xdebug
          tools: composer:2
      - name: Composer
        run: composer install && cd tools/phpunit && composer install
      - name: PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: ./tools/phpunit/vendor/bin/phpunit
      - name: Psalm
        run: ./vendor/bin/psalm