name: 'Unit Tests & Static Analysis'

on:
  push:
    branches: [ release-2.x, release-3.x ]
  pull_request:
    branches: [ release-2.x, release-3.x ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xdebug
          tools: composer:2
      - name: Composer (Annotated Container)
        run: composer install
      - name: Composer (Testing Tools)
        run: cd tools/phpunit && composer install
      - name: Composer (Static Analysis Tools)
        run: cd tools/psalm && composer install
      - name: Composer (Code Linting Tools)
        run: cd tools/labrador-cs && composer install
      - name: Unit Testing
        env:
          XDEBUG_MODE: coverage
        run: ./tools/phpunit/vendor/bin/phpunit
      - name: Psalm
        run: ./tools/psalm/vendor/bin/psalm
      - name: Code Linting
        run: ./tools/labrador-cs/vendor/bin/phpcs --standard=./tools/labrador-cs/vendor/cspray/labrador-coding-standard/ruleset.xml --exclude=Generic.Files.LineLength src test